## Libraries and variables

In [10]:
import pandas as pd

data_path = '../01_Data/'
file_name = 'PSP_Jan_Feb_2019.xlsx'
file_path = data_path + file_name

## Load data and first look
For business understanding it's important to know the data

In [11]:
df = pd.read_excel(file_path, index_col=0)

In [12]:
df.dtypes

tmsp          datetime64[ns]
country               object
amount                 int64
success                int64
PSP                   object
3D_secured             int64
card                  object
dtype: object

In [13]:
# First look at data
df.head(n=50)

,tmsp,country,amount,success,PSP,3D_secured,card
0,2019-01-01 00:01:11,Germany,89,0,UK_Card,0,Visa
1,2019-01-01 00:01:17,Germany,89,1,UK_Card,0,Visa
2,2019-01-01 00:02:49,Germany,238,0,UK_Card,1,Diners
3,2019-01-01 00:03:13,Germany,238,1,UK_Card,1,Diners
4,2019-01-01 00:04:33,Austria,124,0,Simplecard,0,Diners
5,2019-01-01 00:06:41,Switzerland,282,0,UK_Card,0,Master
6,2019-01-01 00:07:19,Switzerland,282,0,Simplecard,0,Master
7,2019-01-01 00:08:46,Germany,117,1,UK_Card,0,Master
8,2019-01-01 00:09:56,Switzerland,174,0,Simplecard,0,Visa
9,2019-01-01 00:10:49,Switzerland,174,0,Simplecard,0,Visa
10,2019-01-01 00:12:15,Austria,232,0,Simplecard,1,Diners
11,2019-01-01 00:12:52,Austria,232,0,UK_Card,1,Diners
12,2019-01-01 00:13:34,Austria,232,0,UK_Card,1,Diners
13,2019-01-01 00:13:44,Austria,232,0,UK_Card,1,Diners
14,2019-01-01 00:14:35,Austria,232,1,UK_Card,1,Diners
15,2019-01-01 00:15:45,Germany,268,0,Simplecard,0,Master
16,2019-01-01 00:18:18,Switzerland,89,0,Simplecard,0,Master
17,2019-01-01 00:18:21,Switzerland,89,0,UK_Card,0,Master
18,2019-01-01 00:18:37,Switzerland,89,0,Moneycard,0,Master
19,2019-01-01 00:20:53,Germany,205,0,UK_Card,0,Master
20,2019-01-01 00:20:56,Germany,205,0,UK_Card,0,Master
21,2019-01-01 00:21:11,Germany,205,1,Moneycard,0,Master
22,2019-01-01 00:23:48,Switzerland,111,0,Simplecard,0,Master
23,2019-01-01 00:24:41,Switzerland,111,0,UK_Card,0,Master
24,2019-01-01 00:24:55,Switzerland,111,0,UK_Card,0,Master
25,2019-01-01 00:25:47,Switzerland,111,0,UK_Card,0,Master
26,2019-01-01 00:26:07,Switzerland,111,0,UK_Card,0,Master
27,2019-01-01 00:26:50,Switzerland,111,0,UK_Card,0,Master
28,2019-01-01 00:28:56,Switzerland,277,1,Goldcard,0,Diners
29,2019-01-01 00:30:50,Switzerland,137,0,UK_Card,0,Diners
30,2019-01-01 00:32:18,Switzerland,148,0,Moneycard,0,Diners
31,2019-01-01 00:34:04,Austria,394,0,UK_Card,0,Diners
32,2019-01-01 00:34:33,Austria,394,0,UK_Card,0,Diners
33,2019-01-01 00:35:25,Austria,394,0,UK_Card,0,Diners
34,2019-01-01 00:35:34,Austria,394,1,UK_Card,0,Diners
35,2019-01-01 00:36:36,Germany,84,0,Moneycard,0,Master
36,2019-01-01 00:41:15,Austria,34,0,Moneycard,0,Visa
37,2019-01-01 00:41:25,Austria,34,0,Simplecard,0,Visa
38,2019-01-01 00:41:43,Austria,34,0,Goldcard,0,Visa
39,2019-01-01 00:44:21,Switzerland,324,0,UK_Card,0,Master
40,2019-01-01 00:46:07,Germany,251,0,UK_Card,1,Master
41,2019-01-01 00:46:34,Germany,251,0,UK_Card,1,Master
42,2019-01-01 00:47:16,Germany,251,0,UK_Card,1,Master
43,2019-01-01 00:47:39,Germany,251,0,Simplecard,1,Master
44,2019-01-01 00:51:27,Germany,100,0,UK_Card,0,Master
45,2019-01-01 00:51:38,Germany,100,0,UK_Card,0,Master
46,2019-01-01 00:52:00,Germany,100,0,UK_Card,0,Master
47,2019-01-01 00:52:04,Germany,100,0,UK_Card,0,Master
48,2019-01-01 00:52:29,Germany,100,0,Simplecard,0,Master
49,2019-01-01 00:55:23,Germany,221,0,Moneycard,0,Visa